# Generated by Django 3.1.7 on 2021-11-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_year', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('unit_file', models.FileField(upload_to='')),
                ('exam_year', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('current_year', models.CharField(max_length=100)),
                ('course_taking', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
