# Generated by Django 3.1.7 on 2021-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
