# Generated by Django 3.1.7 on 2021-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lux', '0002_exams_is_validate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exams',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
