# Generated by Django 3.1.7 on 2021-11-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lux', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visitorcount',
            field=models.IntegerField(default=0),
        ),
    ]
